### ISSUE TITLE
Invalid type for parameter Payload

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#176]
Attempting to perform a simple test results in the above error:

Defining the function works as expected:
```sh
scar init openjdk/7-jre
```
Attempting to run the function:

```
scar run scar-openjdk-7-jre
```
results in the following error:

```
Traceback (most recent call last):
  File "/Users/gmolto/Documents/GitHub/grycap/scar/scar.py", line 894, in <module>
    CmdParser().execute()
  File "/Users/gmolto/Documents/GitHub/grycap/scar/scar.py", line 888, in execute
    args.func(args)
  File "/Users/gmolto/Documents/GitHub/grycap/scar/scar.py", line 234, in run
    response = aws_client.invoke_function(args.name, invocation_type, log_type, payload)
  File "/Users/gmolto/Documents/GitHub/grycap/scar/scar.py", line 757, in invoke_function
    Payload=payload)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 531, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 586, in _convert_to_request_dict
    api_params, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Payload, value: {}, type: <type 'dict'>, valid types: <type 'str'>, <type 'bytearray'>, file-like object
```

**Comment by alpegon** [comment]
Fixed in PR #177
