### ISSUE TITLE
Exception running darknet on Lambda

### ISSUE THREAD

**Issue by Laxenade** [grycap/scar#213]
Trying to deploy darknet on Lambda by running
`python scar.py init -s ./examples/darknet/yolo-sample-object-detection.sh -es fydp-scar grycap/darknet`
It all worked fine until I put an image into the s3 bucket, got following error message from the lambda function.
```
[ERROR]	2018-03-01T06:53:07.707Z	325af9aa-1d1d-11e8-80c7-879198b1da07	Exception launched:
Traceback (most recent call last):
File "/var/task/scar-grycap-darknet.py", line 362, in lambda_handler
pre_process(event)
File "/var/task/scar-grycap-darknet.py", line 140, in pre_process
prepare_udocker_container(os.environ['IMAGE_ID'])
File "/var/task/scar-grycap-darknet.py", line 181, in prepare_udocker_container
cmd_out = subprocess.check_output([udocker_bin, "images"]).decode("utf-8")
File "/var/lang/lib/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/var/lang/lib/python3.6/subprocess.py", line 403, in run
with Popen(*popenargs, **kwargs) as process:
File "/var/lang/lib/python3.6/subprocess.py", line 707, in __init__
restore_signals, start_new_session)
File "/var/lang/lib/python3.6/subprocess.py", line 1326, in _execute_child
raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

**Comment by alpegon** [comment]
Hi, 

I've tried to reproduce your issue and all worked fine for me.

It seems that you could have an issue with the iam permissions, please, check the file:
https://github.com/grycap/scar/blob/master/docs/aws/lambda-execute-role.json
to look at an example of the permissions needed to run scar without problems.

Regards

**Comment by alpegon** [comment]
I'm going to assume that you fixed the problem, if you continue having problems I will reopen the issue.

Regards
