### ISSUE TITLE
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#279]
After creating a function with HTTP support via Event Gateway from the following file:

```sh
functions:
    lambda-scar-cowsay00:
      image: grycap/cowsay
      api_gateway:
        name: cow-api-00
```
by issuing

```sh
scar init -f api-cow.yaml
```
When executing via:
```sh
scar invoke -f api-cow.yaml
```
the following error is obtained:
```sh
Error (Internal Server Error): Traceback (most recent call last):
  File "/var/task/lambda-scar-cowsay00.py", line 163, in lambda_handler
    supervisor.parse_input()
  File "/var/task/lambda-scar-cowsay00.py", line 80, in parse_input
    self.scar_input_file = self.apigateway.save_post_body()
  File "/var/task/src/clients/apigateway.py", line 56, in save_post_body
    return self.save_post_body_file()
  File "/var/task/src/clients/apigateway.py", line 40, in save_post_body_file
    body = base64.b64decode(self.lambda_instance.event['body'])
  File "/var/lang/lib/python3.6/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/var/lang/lib/python3.6/base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

**Comment by alpegon** [comment]
Fixed in PR #281
