### ISSUE TITLE
AWS Batch - S3 Access Denied

### ISSUE THREAD

**Issue by andre-lx** [grycap/scar#301]
Hi. thanks for the project. Everything goes well, but on batch, when the second job it's call (the job responsible for inserting the output into s3), the function returns an error related to S3 permission. 
The role have the AmazonS3FullAccess  policy attached. So I don't understand why the scar can't put the output file there. The job runs for 4 hours. Any questions please let me know.

Traceback (most recent call last):
File "scarbatch_io.py", line 216, in <module>
File "scarbatch_io.py", line 184, in parse_output
File "scarbatch_io.py", line 204, in upload_to_bucket
File "scarbatch_io.py", line 118, in upload_output
File "scarbatch_io.py", line 123, in upload_file
File "boto3/s3/inject.py", line 539, in upload_fileobj
File "s3transfer/futures.py", line 73, in result
File "s3transfer/futures.py", line 233, in result
File "s3transfer/tasks.py", line 126, in __call__
File "s3transfer/tasks.py", line 150, in _execute_main
File "s3transfer/upload.py", line 692, in _main
File "botocore/client.py", line 320, in _api_call
File "botocore/client.py", line 623, in _make_api_call
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
END STEP
OUTPUT BUCKET SET TO scar-gromacs-batch-t6
UPLOADING FILES ['/tmp/4d0c20ad-fc3e-4532-a522-cc692c67ee09/output/md.log']
Uploading file 'gromacs_test_batch_t6/output/4d0c20ad-fc3e-4532-a522-cc692c67ee09/md.log' to bucket 'scar-gromacs-batch-t6'

Another identical error, when the file is too big:

[6] Failed to execute script scarbatch_io
Traceback (most recent call last):
File "scarbatch_io.py", line 216, in <module>
File "scarbatch_io.py", line 184, in parse_output
File "scarbatch_io.py", line 204, in upload_to_bucket
File "scarbatch_io.py", line 118, in upload_output
File "scarbatch_io.py", line 123, in upload_file
File "boto3/s3/inject.py", line 539, in upload_fileobj
File "s3transfer/futures.py", line 73, in result
File "s3transfer/futures.py", line 233, in result
File "s3transfer/tasks.py", line 126, in __call__
File "s3transfer/tasks.py", line 150, in _execute_main
File "s3transfer/tasks.py", line 333, in _main
File "botocore/client.py", line 320, in _api_call
File "botocore/client.py", line 623, in _make_api_call
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
END STEP
OUTPUT BUCKET SET TO scar-gromacs-batch-t5
UPLOADING FILES ['/tmp/40766aca-894d-481c-a5ee-cc740b8f6930/output/input_scar_gromacs_out.tar.gz']
Uploading file 'gromacs_test_batch_t5/output/40766aca-894d-481c-a5ee-cc740b8f6930/input_scar_gromacs_out.tar.gz' to bucket 'scar-gromacs-batch-t5'

Thanks, André Vieira

**Comment by alpegon** [comment]
Hi, 

it looks like you are having an issue with the role policies.
Have in mind that the default role used in the Batch Compute Environments and therefore in the Batch job executions is the **AWSBatchServiceRole**.
Try to attach the **AmazonS3FullAccess** policy to the AWSBatchServiceRole and try again (maybe with a shorter job, just for checking)

Cheers

**Comment by andre-lx** [comment]
Hello again. So my computer environment is using the role:
arn:aws:iam::client_id:role/service-role/AWSBatchServiceRole 

The role contains this two policies:
AmazonS3FullAccess
AWSBatchServiceRole 

----

My lambda function, uses a created role, called lambda_access, and have the follow policies:
AmazonEC2FullAccess
AWSLambdaFullAccess
AmazonS3FullAccess
CloudWatchFullAccess
CloudWatchLogsFullAccess
AWSBatchFullAccess
AmazonECS_FullAccess
AmazonEC2ContainerServiceFullAccess
AmazonECSTaskExecutionRolePolicy
CloudWatchEventsFullAccess 

---
But I get the same error:

[8] Failed to execute script scarbatch_io
Traceback (most recent call last):
File "scarbatch_io.py", line 216, in <module>
File "scarbatch_io.py", line 184, in parse_output
File "scarbatch_io.py", line 204, in upload_to_bucket
File "scarbatch_io.py", line 118, in upload_output
File "scarbatch_io.py", line 123, in upload_file
File "boto3/s3/inject.py", line 539, in upload_fileobj
File "s3transfer/futures.py", line 73, in result
File "s3transfer/futures.py", line 233, in result
File "s3transfer/tasks.py", line 126, in __call__
File "s3transfer/tasks.py", line 150, in _execute_main
File "s3transfer/upload.py", line 692, in _main
File "botocore/client.py", line 320, in _api_call
File "botocore/client.py", line 623, in _make_api_call
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
END STEP
OUTPUT BUCKET SET TO scar-gromacs-batch-t7
UPLOADING FILES ['/tmp/f8271b34-2273-47df-8718-7620b7da8118/output/md.log']
Uploading file 'gromacs_test_batch_t7/output/f8271b34-2273-47df-8718-7620b7da8118/md.log' to bucket 'scar-gromacs-batch-t7'

Thanks, André Vieira

**Comment by gmolto** [comment]
Hi André,

The AmazonS3FullAccess policy should be included in the arn:aws:iam::client_id:instance-profile/**ecsInstanceRole**

If you click on the Compute Environment in AWS Batch, section "Compute Resources" you will see the Instance role used. The IAM policies allocated to that role govern the permissions of the underlying Batch job. 

Please note that you can further restrict an S3 policy to read/write from certain buckets instead of providing jobs with full access to S3.

Let us know if it works and close the issue if so. 

Cheers.

**Comment by andre-lx** [comment]
Hi. 

The problem was, has you mentioned, the S3FullAccess on ecsInstanceRole. 

I forgot about that specific permission.

Sorry for the inconvenience. 

Thanks, André Vieira

**Comment by gmolto** [comment]
Thank your for the feedback.

Updated doc via https://github.com/grycap/scar/pull/303

**Comment by alpegon** [comment]
Glad we could help :)
By the way, this project is part of my PhD Thesis and I'm looking for different use cases

**Comment by andre-lx** [comment]
@alpegon I will send you an e-mail. However in the near future I want to make a pull request to the examples of your project.

**Comment by alpegon** [comment]
That's great, thank you very much.
