### ISSUE TITLE
Unable to Install SCAR in Vanilla Ubuntu 18.04

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#312]
Attempting to install SCAR trough pip3 on a vanilla Ubuntu 18.04 vagrant box via:
```pip3 install scar ```
results in the following error:

```
collecting faas-supervisor (from scar)
  Downloading https://files.pythonhosted.org/packages/06/d3/0b290542f7fe507925f2819c36d997c106123b8828ae51c8c802381a0ec9/faas-supervisor-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cxgwa4i0/faas-supervisor/setup.py", line 15, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cxgwa4i0/faas-supervisor/
```

**Comment by alpegon** [comment]
This problems occurs when trying to install scar without updating the python setuptools package to a version equal or greater than 40.8.0.
I've updated the requirements file and the instructions to install scar.
Please, try to install it again following the new instructions.

**Comment by gmolto** [comment]
Solved. Thanks.
