### ISSUE TITLE
Intermiten error using Batch mode

### ISSUE THREAD

**Issue by adolfomendezcr** [grycap/scar#323]
Hi, 
I´m facing an issue using SCAR in Batch mode. Most of the times the job execution works ok but sometimes I´m getting an error starting the container:

Status reasonTask failed to start
Container messageCannotStartContainerError: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/tmp/tmp2ugukqah/script.sh\": stat /tmp/tmp2ugukqah/script.sh: no such file or directory": unknown

the configuration files I´m using is:

functions:
  amendez-diagnostico-arritmias:
    image: adolfomendezcr/amendez_caso_estudio
    memory: 512
    init_script: diagnostico_arritmia.sh
    execution_mode: batch
    s3:
      input_bucket: amendez-bucket-intermedio-3
      output_bucket: amendez-bucket-envio-resultados/amendez-envio-resultado/input

and the shell script is:
echo "SCRIPT: Ejecutando Algoritmo entrada: $INPUT_FILE_PATH"
python mult2.py  -i $INPUT_FILE_PATH -o $TMP_OUTPUT_DIR/batch.result.txt

mult2.py is a python script that multiply the contend in the input file by 2.

**Comment by alpegon** [comment]
Hi, it looks like the supervisor inside the container is not finding the script to execute.
The next time the error happens, please attach also the information of the input job, that is, the job that downloads the information and stores it in the temporal folders.
I want to see if the temporal folders of the input job and the container job match to be able to continue with the debugging.

Thanks

**Comment by adolfomendezcr** [comment]
Hi, It fail again today,

The in job works here is the log:


19:42:51
2019-06-04 19:42:51,200 - supervisor - INFO - Received event: {'Records': [{'eventVersion': '2.1', 'eventSource': 'aws:s3', 'awsRegion': 'us-east-1', 'eventTime': '2019-06-04T19:35:32.688Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'AWS:AROAJCFPUNQW5VJZJBZNM:amendez-filtrado-sensor-electrico'}, 'requestParameters': {'sourceIPAddress': '3.95.5.150'}, 'responseElements': {'x
2019-06-04 19:42:51,200 - supervisor - INFO - Received event: {'Records': [{'eventVersion': '2.1', 'eventSource': 'aws:s3', 'awsRegion': 'us-east-1', 'eventTime': '2019-06-04T19:35:32.688Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'AWS:AROAJCFPUNQW5VJZJBZNM:amendez-filtrado-sensor-electrico'}, 'requestParameters': {'sourceIPAddress': '3.95.5.150'}, 'responseElements': {'x-amz-request-id': 'F7A089D0FA287468', 'x-amz-id-2': 'H5DCJqfMdP/EXYakwDO2YjNDQvsWHcSoFpNg/Cd7gcAeVldvOckClQfoOLnjEMaB3SSKyg5qQH8='}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': 'NDA5MDExMGUtMjczYy00NjBkLWEwZWUtNjc4YzE3Mjk0N2Zm', 'bucket': {'name': 'amendez-bucket-intermedio-3', 'ownerIdentity': {'principalId': 'A3DGHIUEZTUZ9H'}, 'arn': 'arn:aws:s3:::amendez-bucket-intermedio-3'}, 'object': {'key': 'amendez-diagnostico-arritmias/input/container-stdout.txt', 'size': 181, 'eTag': '177820d6ffd4d89d028ee8cfbdb3862d', 'sequencer': '005CF6C804935BB1F6'}}}]}

19:42:51
2019-06-04 19:42:51,200 - supervisor - INFO - Analizing storage event
2019-06-04 19:42:51,200 - supervisor - INFO - Analizing storage event

19:42:51
2019-06-04 19:42:51,200 - supervisor - INFO - S3 event created
2019-06-04 19:42:51,200 - supervisor - INFO - S3 event created

19:42:51
2019-06-04 19:42:51,201 - supervisor - INFO - A copy of the JSON event has been saved in the path '/tmp/tmpu2c6ag9a/event.json'
2019-06-04 19:42:51,201 - supervisor - INFO - A copy of the JSON event has been saved in the path '/tmp/tmpu2c6ag9a/event.json'

19:42:51
2019-06-04 19:42:51,212 - supervisor - INFO - SUPERVISOR: Initializing AWS Batch supervisor
2019-06-04 19:42:51,212 - supervisor - INFO - SUPERVISOR: Initializing AWS Batch supervisor

19:42:51
2019-06-04 19:42:51,213 - supervisor - INFO - Reading STORAGE_AUTH variables
2019-06-04 19:42:51,213 - supervisor - INFO - Reading STORAGE_AUTH variables

19:42:51
2019-06-04 19:42:51,213 - supervisor - INFO - Reading STORAGE_PATH variables
2019-06-04 19:42:51,213 - supervisor - INFO - Reading STORAGE_PATH variables

19:42:51
2019-06-04 19:42:51,402 - supervisor - INFO - Found 'S3' input provider
2019-06-04 19:42:51,402 - supervisor - INFO - Found 'S3' input provider

19:42:51
2019-06-04 19:42:51,403 - supervisor - INFO - Found 'S3' output provider
2019-06-04 19:42:51,403 - supervisor - INFO - Found 'S3' output provider

19:42:51
2019-06-04 19:42:51,403 - supervisor - INFO - Script file created in '/tmp/tmpu2c6ag9a/script.sh'
2019-06-04 19:42:51,403 - supervisor - INFO - Script file created in '/tmp/tmpu2c6ag9a/script.sh'

19:42:51
2019-06-04 19:42:51,415 - supervisor - INFO - Downloading input file from event type 'S3'
2019-06-04 19:42:51,415 - supervisor - INFO - Downloading input file from event type 'S3'

19:42:51
2019-06-04 19:42:51,415 - supervisor - INFO - Downloading item from bucket 'amendez-bucket-intermedio-3' with key 'amendez-diagnostico-arritmias/input/container-stdout.txt'
2019-06-04 19:42:51,415 - supervisor - INFO - Downloading item from bucket 'amendez-bucket-intermedio-3' with key 'amendez-diagnostico-arritmias/input/container-stdout.txt'

19:42:51
2019-06-04 19:42:51,854 - supervisor - INFO - Successful download of file 'amendez-diagnostico-arritmias/input/container-stdout.txt' from bucket 'amendez-bucket-intermedio-3' in path '/tmp/tmpu2c6ag9a/container-stdout.txt'
2019-06-04 19:42:51,854 - supervisor - INFO - Successful download of file 'amendez-diagnostico-arritmias/input/container-stdout.txt' from bucket 'amendez-bucket-intermedio-3' in path '/tmp/tmpu2c6ag9a/container-stdout.txt'

19:42:51
2019-06-04 19:42:51,855 - supervisor - INFO - INPUT_FILE_PATH variable set to '/tmp/tmpu2c6ag9a/container-stdout.txt'
2019-06-04 19:42:51,855 - supervisor - INFO - INPUT_FILE_PATH variable set to '/tmp/tmpu2c6ag9a/container-stdout.txt'

19:42:51
2019-06-04 19:42:51,855 - supervisor - INFO - Creating response
2019-06-04 19:42:51,855 - supervisor - INFO - Creating response


here is the failing log for the second job:

Reason: CannotStartContainerError: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/tmp/tmpu2c6ag9a/script.sh\": stat /tmp/tmpu2c6ag9a/script.sh: no such file or directory": unknown


and also the output job failed:

Status reasonDependent Job failed
Container message

**Comment by alpegon** [comment]
Thanks for the info.

Just to inform you, we are going to heavily modify the way that scar is using batch right now.
When it's finished you will be able to set the batch configuration in the scar configuration file or in the function definition file and we plan to reduce the batch jobs from 3 to 1, so the batch execution is faster.

The good news are that we think this modifications can solve your problem.
The bad news are that the refactorization cannot be done in a week, so you'll have to be patient.
I will leave this issue open and I'll notify you when the update is done.

Cheers

**Comment by alpegon** [comment]
Hi, sorry for the delay, but we finally managed to update the batch management.

Among other things, we've updated the configuration file of scar to allow the users more flexibility when defining batch environments.
Now scar only creates one job in batch to do the required task, however to allow this functionality to work, you need to update your AWS permissions. Your user will need permission to manage LaunchTemplates (create and list). In the following weeks we will update the documentation to reflect all the new changes. 

I hope that with these changes your batch error is solved, when we were testing the batch functionality we weren't able to reproduce your error.
Anyway if you have any doubts or suggestions feel free to ask.

Regards

**Comment by adolfomendezcr** [comment]
Hi again,
thanks for the help with the issue. I tried with the new version using the mrbayes example but Iñm getting an error with the faassupervisor layer:

[Errno 21] Is a directory: '/tmp/tmpfijmxb8a/': IsADirectoryError
Traceback (most recent call last):
File "/var/task/amendez-scar-mrbayes-batch.py", line 21, in lambda_handler
return supervisor.main(event=event, context=context)
File "/opt/python/faassupervisor/supervisor.py", line 138, in main
return supervisor.run()
File "/opt/python/faassupervisor/exceptions.py", line 30, in wrapper
return func(*args, **kwargs)
File "/opt/python/faassupervisor/supervisor.py", line 102, in run
self._parse_input()
File "/opt/python/faassupervisor/exceptions.py", line 30, in wrapper
return func(*args, **kwargs)
File "/opt/python/faassupervisor/supervisor.py", line 87, in _parse_input
SysUtils.get_env_var("TMP_INPUT_DIR"))
File "/opt/python/faassupervisor/storage/__init__.py", line 51, in download_input
return storage_provider.download_file(parsed_event, input_dir_path)
File "/opt/python/faassupervisor/storage/providers/s3.py", line 62, in download_file
with open(file_download_path, 'wb') as data:
IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpfijmxb8a/'


is there any way of remove the faassupervisor ?

Thanks in advance for the help

**Comment by srisco** [comment]
Hi Adolfo, 
we've recently found a bug in layer creation and update process and probably your issue is related to it.

> is there any way of remove the faassupervisor ?

At the moment, the AWS Lambda API only allows to delete specific lambda layer versions and deleting them is not supported by scar. However, you can delete versions from the AWS console or using aws-cli.

Please, to use an updated supervisor delete your function and try to create a new one passing the parameter `-sv` with the latest version of faas-supervisor (`1.1.1` at this moment) and check if the issue persists.

I hope this solves your problem while we fix the bug.

Regards.

**Comment by adolfomendezcr** [comment]
Hi Sebas,

Thank you for the help, I will give a try tonight.

Regards,
Adolfo

**Comment by adolfomendezcr** [comment]
Hi Sebas,

I tried with sv version 1.1.1 but I'm getting the same error:

[Errno 21] Is a directory: '/tmp/tmpq9kdowd3/': IsADirectoryError
Traceback (most recent call last):
File "/var/task/amendez-scar-mrbayes-batch.py", line 21, in lambda_handler
return supervisor.main(event=event, context=context)
File "/opt/python/faassupervisor/supervisor.py", line 138, in main
return supervisor.run()
File "/opt/python/faassupervisor/exceptions.py", line 30, in wrapper
return func(*args, **kwargs)
File "/opt/python/faassupervisor/supervisor.py", line 102, in run
self._parse_input()
File "/opt/python/faassupervisor/exceptions.py", line 30, in wrapper
return func(*args, **kwargs)
File "/opt/python/faassupervisor/supervisor.py", line 87, in _parse_input
SysUtils.get_env_var("TMP_INPUT_DIR"))
File "/opt/python/faassupervisor/storage/__init__.py", line 51, in download_input
return storage_provider.download_file(parsed_event, input_dir_path)
File "/opt/python/faassupervisor/storage/providers/s3.py", line 62, in download_file
with open(file_download_path, 'wb') as data:
IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpq9kdowd3/'

regards,
Adolfo

**Comment by srisco** [comment]
Hello Adolfo, sorry for the delay.

I just reproduced the use case and I think the problem is on the documentation. The user script (mrbayes-sample-run.sh), as well as the faas-supervisor, needs an input file, so running it via `scar run` is always getting the same error because no input file is provided. In order to properly execute the example you have to upload to the s3 input bucket the file `cynmix.nex`.

Anyways I will discuss with @alpegon if we support empty events in the faas-supervisor.

Regards.

**Comment by adolfomendezcr** [comment]
Hi Sebas,

I'm passing the file using awscli, I'm copying the fili directly in the input bucket. Anyway I will double check the directory name this afternoon and let you now. 

Thank you for the help,

Adolfo

**Comment by adolfomendezcr** [comment]
Hi Sebas, 
Batch is working fine, thanks for the help
