### ISSUE TITLE
JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by WinstonN** [grycap/scar#353]
Hello

Following the docs, brand new to scar, trying the cowsay example, I get

```
~ $ scar init -n scar-cowsay -i grycap/cowsay
the JSON object must be str, bytes or bytearray, not NoneType
```

I'm not sure how to fix it? Could you please give me some advice?
Thanks!

**Comment by srisco** [comment]
Hi @WinstonN, thank you for using scar.

The latest version shouldn't give you that error. Could you tell me the SCAR version you have installed?
```
scar --version
```

I recommend you to install the latest version available on [PyPi](https://pypi.org/project/scar/) by following [these instructions](https://scar.readthedocs.io/en/latest/installation.html#install-using-pip3).

**Comment by WinstonN** [comment]
Apologies for not adding it
My version is, 
```
~ $ scar --version
SCAR 4.0.1
```
I think I am on the latest and built the docker container as the docs explained

**Comment by srisco** [comment]
If you are running the latest version of SCAR that error is caused by some problem in the configuration file. As I see that you are using a container, please check that the `.scar` configuration folder is correctly mounted
```
docker run -it -v $AWS_CREDENTIALS_FOLDER:/home/scar/.aws -v $SCAR_CONFIG_FOLDER:/home/scar/.scar scar
```
and that you have a `scar.cfg` [configuration file](https://scar.readthedocs.io/en/latest/configuration.html#configuration-file) inside.

**Comment by WinstonN** [comment]
hello @srisco 
Thank you for the help, 

I am making progress but hit the following errors

1. is not authorized to perform: lambda:ListLayerVersions on resource
```
2020-05-09 00:06:02,366 - root - INFO - ----------------------------------------------------
2020-05-09 00:06:02,367 - root - INFO - SCAR execution started
2020-05-09 00:06:02,438 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-05-09 00:06:04,616 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-05-09 00:06:06,150 - root - INFO - Using latest supervisor release: '1.2.3'.
2020-05-09 00:06:13,200 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-05-09 00:06:13,684 - root - ERROR - An error occurred (AccessDeniedException) when calling the ListLayerVersions operation: User: arn:aws:iam::889109177196:user/scar-docker-in-lambda is not authorized to perform: lambda:ListLayerVersions on resource: arn:aws:lambda:ap-southeast-2:889109177196:layer:faas-supervisor
Traceback (most recent call last):
  File "/home/scar/.local/lib/python3.8/site-packages/scar/exceptions.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/scar/.local/lib/python3.8/site-packages/scar/providers/aws/clients/lambdafunction.py", line 114, in list_layer_versions
    layer_versions_info = self.client.list_layer_versions(**kwargs)
  File "/home/scar/.local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/scar/.local/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the ListLayerVersions operation: User: arn:aws:iam::889109177196:user/scar-docker-in-lambda is not authorized to perform: lambda:ListLayerVersions on resource: arn:aws:lambda:ap-southeast-2:889109177196:layer:faas-supervisor
```
I then added the right resources to my policy - and the error went away

2. The tag '1.2.3' was not found in the GitHub repository
I need help here
```
2020-05-09 00:07:10,778 - root - INFO - ----------------------------------------------------
2020-05-09 00:07:10,779 - root - INFO - SCAR execution started
2020-05-09 00:07:10,903 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-05-09 00:07:12,987 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-05-09 00:07:17,250 - root - INFO - Using latest supervisor release: '1.2.3'.
2020-05-09 00:07:17,541 - root - ERROR - The tag '1.2.3' was not found in the GitHub repository.
Traceback (most recent call last):
  File "/home/scar/.local/lib/python3.8/site-packages/scar/exceptions.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/scar/.local/lib/python3.8/site-packages/scar/providers/aws/lambdafunction.py", line 78, in create_function
    supervisor_zip_path = SupervisorUtils.download_supervisor(
  File "/home/scar/.local/lib/python3.8/site-packages/scar/utils.py", line 464, in download_supervisor
    supervisor_zip_url = GitHubUtils.get_source_code_url(
  File "/home/scar/.local/lib/python3.8/site-packages/scar/utils.py", line 444, in get_source_code_url
    raise GitHubTagNotFoundError(tag=tag_name)
scar.exceptions.GitHubTagNotFoundError: The tag '1.2.3' was not found in the GitHub repository.
```

When I ran the command `scar init -n scar-cowsay -i grycap/cowsay` again, I get the error I got originally

3. root - ERROR - the JSON object must be str, bytes or bytearray, not NoneType 
I need help here
```
2020-05-09 00:08:09,462 - root - INFO - ----------------------------------------------------
2020-05-09 00:08:09,463 - root - INFO - SCAR execution started
2020-05-09 00:08:09,537 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-05-09 00:08:11,546 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-05-09 00:08:12,601 - root - ERROR - the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "/home/scar/.local/lib/python3.8/site-packages/scar/scarcli.py", line 59, in main
    AWS(func_call)
  File "/home/scar/.local/lib/python3.8/site-packages/scar/providers/aws/controller.py", line 139, in __init__
    getattr(self, func_call)()
  File "/home/scar/.local/lib/python3.8/site-packages/scar/exceptions.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/scar/.local/lib/python3.8/site-packages/scar/providers/aws/controller.py", line 153, in init
    resources_info['lambda']['supervisor']['version'] = SupervisorUtils.check_supervisor_version(
  File "/home/scar/.local/lib/python3.8/site-packages/scar/utils.py", line 480, in check_supervisor_version
    latest_version = SupervisorUtils.get_latest_release()
  File "/home/scar/.local/lib/python3.8/site-packages/scar/utils.py", line 497, in get_latest_release
    return GitHubUtils.get_latest_release(cls._SUPERVISOR_GITHUB_USER,
  File "/home/scar/.local/lib/python3.8/site-packages/scar/utils.py", line 400, in get_latest_release
    response = json.loads(request.get_file(url))
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
2020-05-09 00:08:12,606 - root - INFO - SCAR execution finished with errors
```

I'll debug it further but thought I would post here

**Comment by WinstonN** [comment]
These issues resolved by themselves and I can no longer produce them accurately. 
Closing this issue
